apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mongodb-operator
  namespace: l5e
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: community-operator
      sourceRef:
        kind: HelmRepository
        name: mongodb-community
        namespace: l5e
      version: "0.9.0"
  install:
    crds: Create
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    crds: Create
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    operator:
      watchNamespace: l5e
    podSecurityPolicy:
      enabled: false
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi
