apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: l5e-es
  namespace: l5e
spec:
  interval: 5m
  chart:
    spec:
      chart: community-operator
      sourceRef:
        kind: HelmRepository
        name: mongodb-community
        namespace: l5e
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: Create
  values:
    operator:
      watchNamespace: l5e
    podSecurityPolicy:
      enabled: false
