apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: l5e-es
namespace: l5e
resources:
  - mongodb-helmrepo.yaml
  - mongodb-operator-release.yaml
  - mongodb-storage.yaml
  - mongodb-secret.yaml
  - mongodb-instance.yaml
