apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: l5e-es
  namespace: l5e
spec:
  members: 1
  type: ReplicaSet
  version: "7.0. 0"
  security:
    tls:
      enabled: false
    authentication:
      modes: ["SCRAM"]
    roles:
      - role: root
        db: admin
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-secret
      roles:
        - name: root
          db: admin
    - name: eventstore
      db: eventstore
      passwordSecretRef:
        name: mongodb-eventstore-secret
      roles:
        - name: readWrite
          db: eventstore
        - name: dbAdmin
          db: eventstore
  additionalMongodConfig:
    net:
      maxIncomingConnections: 200
      unixDomainSocket:
        enabled: true
    security:
      authorization: enabled
  statefulSet:
    spec:
      selector: {}
      serviceName: l5e-es-svc
      replicas: 1
      template:
        metadata: {}
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - toph
          containers:
            - name: mongod
              image: mongo:7.0.0
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi
              volumeMounts:
                - name: logs
                  mountPath: /var/log/mongodb
                - name: data
                  mountPath: /data/db
          volumes:
            - name: logs
              emptyDir: {}
            - name: data
              persistentVolumeClaim:
                claimName: pvc-mongodb-data
