apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: l5e-mongo
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet

  version: "7.0.5"

  security:
    authentication:
      modes: ["SCRAM"]

  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: sc-at-1-mongo
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

  users:
    - name: app-user
      db: admin
      passwordSecretRef:
        name: mongo-app-user-password
      roles:
        - name: readWrite
          db: l5e

