apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-community-operator
  namespace: l5e
spec:
  interval: 10m
  chart:
    spec:
      chart: community-operator
      version: "0.10.0" # Check for the latest compatible version
      sourceRef:
        kind: HelmRepository
        name: mongodb-charts
        namespace: l5e
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
