apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-mongodb
  local:
    path: /run/media/at-1/mongodb-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - toph
