apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-at-1-mongo
  namespace: mongodb
spec:
  storageClassName: sc-at-1-mongo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

