apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-at-1-l5e-rs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-at-1-l5e-rs
  local:
    path: /run/media/at-1/l5e-rs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - toph
