apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: l5e-es
  namespace: l5e
spec:
  interval: 5m
  chart:
    spec:
      chart: mongodb
      version: "14.13.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system 
  values:
    architecture: standalone

    auth:
      enabled: true
      rootUser: root
      existingSecret: l5e-es-admin-credentials
      existingSecretPasswordKey: mongodb-root-password

    persistence:
      enabled: true
      storageClass: sc-at-1-l5e-es
      size: 10Gi

    volumePermissions:
      enabled: true
