apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: l5e-es-ingress
  namespace: l5e
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: "es.jinora.lan"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: l5e-es
                port:
                  number: 27017
