apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: l5e
resources:
  - namespace.yaml
  - storageclass.yaml
  - pv.yaml
  - secret.yaml
  - helm-release.yaml   # <--- ADD THIS
  - bitnami-helm-repository.yaml
