apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mongodb-instance
  namespace: l5e
resources:
  - storageclass.yaml
  - pv-l5e-es-data.yaml
  - pv-l5e-es-logs.yaml
  - service.yaml
  - mongodb-cr.yaml
  - l5e-es-admin-password.yaml
