apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-l5e-es-logs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-l5e-es
  local:
    path: /run/media/at-1/es
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - toph

