apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-at-1-mongo
  namespace: l5e
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-at-1-mongodb
