apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb-data
  namespace: l5e
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-mongodb
