apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - kustomization.yaml
  - namespace.yaml
  - service.yaml
  - storageclass.yaml
  - pv.yaml
  - pvc.yaml
