apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-at-1-cdn
  namespace: l5e
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-at-1-cdn
