apiVersion: v1
kind: Service
metadata:
  name: cdn
  namespace: l5e
  labels:
    app: l5e-cdn
    release: kube-prometheus-stack
spec:
  type: ClusterIP
  selector:
    app: l5e-cdn
  ports:
    - port: 3000
      targetPort: 3000
