apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: l5e-cdn
  namespace: l5e
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - l5e
  selector:
    matchLabels:
      app: l5e-cdn
  endpoints:
    - targetPort: 3000
      path: /api/metrics
      scheme: http
